// ===== Pokemon Data for SV =====
// name: Japanese name, slug: Showdown sprite name (no hyphens in base names), dex: national dex number
const POKEMON_LIST = [
  { name: "フシギバナ", slug: "venusaur", dex: 3 },
  { name: "リザードン", slug: "charizard", dex: 6 },
  { name: "カメックス", slug: "blastoise", dex: 9 },
  { name: "バタフリー", slug: "butterfree", dex: 12 },
  { name: "ピカチュウ", slug: "pikachu", dex: 25 },
  { name: "ライチュウ", slug: "raichu", dex: 26 },
  { name: "ニドクイン", slug: "nidoqueen", dex: 31 },
  { name: "ニドキング", slug: "nidoking", dex: 34 },
  { name: "ピクシー", slug: "clefable", dex: 36 },
  { name: "キュウコン", slug: "ninetales", dex: 38 },
  { name: "プクリン", slug: "wigglytuff", dex: 40 },
  { name: "ゴルバット", slug: "golbat", dex: 42 },
  { name: "ラフレシア", slug: "vileplume", dex: 45 },
  { name: "パラセクト", slug: "parasect", dex: 47 },
  { name: "ダグトリオ", slug: "dugtrio", dex: 51 },
  { name: "ペルシアン", slug: "persian", dex: 53 },
  { name: "ゴルダック", slug: "golduck", dex: 55 },
  { name: "オコリザル", slug: "primeape", dex: 57 },
  { name: "ウインディ", slug: "arcanine", dex: 59 },
  { name: "ニョロボン", slug: "poliwrath", dex: 62 },
  { name: "フーディン", slug: "alakazam", dex: 65 },
  { name: "カイリキー", slug: "machamp", dex: 68 },
  { name: "ウツボット", slug: "victreebel", dex: 71 },
  { name: "ドククラゲ", slug: "tentacruel", dex: 73 },
  { name: "ゴローニャ", slug: "golem", dex: 76 },
  { name: "ギャロップ", slug: "rapidash", dex: 78 },
  { name: "ヤドラン", slug: "slowbro", dex: 80 },
  { name: "レアコイル", slug: "magneton", dex: 82 },
  { name: "ドードリオ", slug: "dodrio", dex: 85 },
  { name: "ジュゴン", slug: "dewgong", dex: 87 },
  { name: "ベトベトン", slug: "muk", dex: 89 },
  { name: "ゲンガー", slug: "gengar", dex: 94 },
  { name: "スリーパー", slug: "hypno", dex: 97 },
  { name: "キングラー", slug: "kingler", dex: 99 },
  { name: "ナッシー", slug: "exeggutor", dex: 103 },
  { name: "ガラガラ", slug: "marowak", dex: 105 },
  { name: "サワムラー", slug: "hitmonlee", dex: 106 },
  { name: "エビワラー", slug: "hitmonchan", dex: 107 },
  { name: "ベロリンガ", slug: "lickitung", dex: 108 },
  { name: "マタドガス", slug: "weezing", dex: 110 },
  { name: "サイドン", slug: "rhydon", dex: 112 },
  { name: "ラッキー", slug: "chansey", dex: 113 },
  { name: "モンジャラ", slug: "tangela", dex: 114 },
  { name: "ガルーラ", slug: "kangaskhan", dex: 115 },
  { name: "アズマオウ", slug: "seaking", dex: 119 },
  { name: "スターミー", slug: "starmie", dex: 121 },
  { name: "バリヤード", slug: "mrmime", dex: 122 },
  { name: "ストライク", slug: "scyther", dex: 123 },
  { name: "ルージュラ", slug: "jynx", dex: 124 },
  { name: "エレブー", slug: "electabuzz", dex: 125 },
  { name: "ブーバー", slug: "magmar", dex: 126 },
  { name: "カイロス", slug: "pinsir", dex: 127 },
  { name: "ケンタロス", slug: "tauros", dex: 128 },
  { name: "ギャラドス", slug: "gyarados", dex: 130 },
  { name: "ラプラス", slug: "lapras", dex: 131 },
  { name: "メタモン", slug: "ditto", dex: 132 },
  { name: "シャワーズ", slug: "vaporeon", dex: 134 },
  { name: "サンダース", slug: "jolteon", dex: 135 },
  { name: "ブースター", slug: "flareon", dex: 136 },
  { name: "カビゴン", slug: "snorlax", dex: 143 },
  { name: "フリーザー", slug: "articuno", dex: 144 },
  { name: "サンダー", slug: "zapdos", dex: 145 },
  { name: "ファイヤー", slug: "moltres", dex: 146 },
  { name: "カイリュー", slug: "dragonite", dex: 149 },
  { name: "ミュウツー", slug: "mewtwo", dex: 150 },
  { name: "チコリータ", slug: "chikorita", dex: 152 },
  { name: "メガニウム", slug: "meganium", dex: 154 },
  { name: "バクフーン", slug: "typhlosion", dex: 157 },
  { name: "オーダイル", slug: "feraligatr", dex: 160 },
  { name: "ヌオー", slug: "quagsire", dex: 195 },
  { name: "エーフィ", slug: "espeon", dex: 196 },
  { name: "ブラッキー", slug: "umbreon", dex: 197 },
  { name: "ヤミカラス", slug: "murkrow", dex: 198 },
  { name: "ヤドキング", slug: "slowking", dex: 199 },
  { name: "ハガネール", slug: "steelix", dex: 208 },
  { name: "ハッサム", slug: "scizor", dex: 212 },
  { name: "ヘラクロス", slug: "heracross", dex: 214 },
  { name: "ニューラ", slug: "sneasel", dex: 215 },
  { name: "リングマ", slug: "ursaring", dex: 217 },
  { name: "ドンファン", slug: "donphan", dex: 232 },
  { name: "ドーブル", slug: "smeargle", dex: 235 },
  { name: "ミルタンク", slug: "miltank", dex: 241 },
  { name: "ハピナス", slug: "blissey", dex: 242 },
  { name: "ライコウ", slug: "raikou", dex: 243 },
  { name: "エンテイ", slug: "entei", dex: 244 },
  { name: "スイクン", slug: "suicune", dex: 245 },
  { name: "バンギラス", slug: "tyranitar", dex: 248 },
  { name: "ルギア", slug: "lugia", dex: 249 },
  { name: "ホウオウ", slug: "hooh", dex: 250 },
  { name: "ジュカイン", slug: "sceptile", dex: 254 },
  { name: "バシャーモ", slug: "blaziken", dex: 257 },
  { name: "ラグラージ", slug: "swampert", dex: 260 },
  { name: "グラエナ", slug: "mightyena", dex: 262 },
  { name: "ペリッパー", slug: "pelipper", dex: 279 },
  { name: "サーナイト", slug: "gardevoir", dex: 282 },
  { name: "キノガッサ", slug: "breloom", dex: 286 },
  { name: "ヤミラミ", slug: "sableye", dex: 302 },
  { name: "クチート", slug: "mawile", dex: 303 },
  { name: "ボスゴドラ", slug: "aggron", dex: 306 },
  { name: "チャーレム", slug: "medicham", dex: 308 },
  { name: "ライボルト", slug: "manectric", dex: 310 },
  { name: "サメハダー", slug: "sharpedo", dex: 319 },
  { name: "バクーダ", slug: "camerupt", dex: 323 },
  { name: "コータス", slug: "torkoal", dex: 324 },
  { name: "フライゴン", slug: "flygon", dex: 330 },
  { name: "ザングース", slug: "zangoose", dex: 335 },
  { name: "ハブネーク", slug: "seviper", dex: 336 },
  { name: "ルナトーン", slug: "lunatone", dex: 337 },
  { name: "ソルロック", slug: "solrock", dex: 338 },
  { name: "ナマズン", slug: "whiscash", dex: 340 },
  { name: "ミロカロス", slug: "milotic", dex: 350 },
  { name: "トロピウス", slug: "tropius", dex: 357 },
  { name: "アブソル", slug: "absol", dex: 359 },
  { name: "ボーマンダ", slug: "salamence", dex: 373 },
  { name: "メタグロス", slug: "metagross", dex: 376 },
  { name: "ラティアス", slug: "latias", dex: 380 },
  { name: "ラティオス", slug: "latios", dex: 381 },
  { name: "カイオーガ", slug: "kyogre", dex: 382 },
  { name: "グラードン", slug: "groudon", dex: 383 },
  { name: "レックウザ", slug: "rayquaza", dex: 384 },
  { name: "ドダイトス", slug: "torterra", dex: 389 },
  { name: "ゴウカザル", slug: "infernape", dex: 392 },
  { name: "エンペルト", slug: "empoleon", dex: 395 },
  { name: "ムクホーク", slug: "staraptor", dex: 398 },
  { name: "レントラー", slug: "luxray", dex: 405 },
  { name: "ロズレイド", slug: "roserade", dex: 407 },
  { name: "ミカルゲ", slug: "spiritomb", dex: 442 },
  { name: "ガブリアス", slug: "garchomp", dex: 445 },
  { name: "ルカリオ", slug: "lucario", dex: 448 },
  { name: "カバルドン", slug: "hippowdon", dex: 450 },
  { name: "ドラピオン", slug: "drapion", dex: 452 },
  { name: "マニューラ", slug: "weavile", dex: 461 },
  { name: "ジバコイル", slug: "magnezone", dex: 462 },
  { name: "ドサイドン", slug: "rhyperior", dex: 464 },
  { name: "エレキブル", slug: "electivire", dex: 466 },
  { name: "ブーバーン", slug: "magmortar", dex: 467 },
  { name: "トゲキッス", slug: "togekiss", dex: 468 },
  { name: "リーフィア", slug: "leafeon", dex: 470 },
  { name: "グレイシア", slug: "glaceon", dex: 471 },
  { name: "グライオン", slug: "gliscor", dex: 472 },
  { name: "マンムー", slug: "mamoswine", dex: 473 },
  { name: "ポリゴンZ", slug: "porygonz", dex: 474 },
  { name: "エルレイド", slug: "gallade", dex: 475 },
  { name: "ヨノワール", slug: "dusknoir", dex: 477 },
  { name: "ユキメノコ", slug: "froslass", dex: 478 },
  { name: "ロトム", slug: "rotom", dex: 479 },
  { name: "ヒートロトム", slug: "rotom-heat", dex: 479 },
  { name: "ウォッシュロトム", slug: "rotom-wash", dex: 479 },
  { name: "カットロトム", slug: "rotom-mow", dex: 479 },
  { name: "フロストロトム", slug: "rotom-frost", dex: 479 },
  { name: "スピンロトム", slug: "rotom-fan", dex: 479 },
  { name: "ディアルガ", slug: "dialga", dex: 483 },
  { name: "パルキア", slug: "palkia", dex: 484 },
  { name: "ギラティナ", slug: "giratina", dex: 487 },
  { name: "ダークライ", slug: "darkrai", dex: 491 },
  { name: "アルセウス", slug: "arceus", dex: 493 },
  { name: "ジャローダ", slug: "serperior", dex: 497 },
  { name: "エンブオー", slug: "emboar", dex: 500 },
  { name: "ダイケンキ", slug: "samurott", dex: 503 },
  { name: "ムーランド", slug: "stoutland", dex: 508 },
  { name: "ドリュウズ", slug: "excadrill", dex: 530 },
  { name: "ローブシン", slug: "conkeldurr", dex: 534 },
  { name: "エルフーン", slug: "whimsicott", dex: 547 },
  { name: "ドレディア", slug: "lilligant", dex: 549 },
  { name: "ゾロアーク", slug: "zoroark", dex: 571 },
  { name: "モロバレル", slug: "amoonguss", dex: 591 },
  { name: "ママンボウ", slug: "alomomola", dex: 594 },
  { name: "ウォーグル", slug: "braviary", dex: 628 },
  { name: "サザンドラ", slug: "hydreigon", dex: 635 },
  { name: "ボルトロス", slug: "thundurus", dex: 642 },
  { name: "レシラム", slug: "reshiram", dex: 643 },
  { name: "ゼクロム", slug: "zekrom", dex: 644 },
  { name: "ランドロス", slug: "landorus", dex: 645 },
  { name: "キュレム", slug: "kyurem", dex: 646 },
  { name: "ゲッコウガ", slug: "greninja", dex: 658 },
  { name: "ファイアロー", slug: "talonflame", dex: 663 },
  { name: "ギルガルド", slug: "aegislash", dex: 681 },
  { name: "ニンフィア", slug: "sylveon", dex: 700 },
  { name: "ヌメルゴン", slug: "goodra", dex: 706 },
  { name: "クレッフィ", slug: "klefki", dex: 707 },
  { name: "オンバーン", slug: "noivern", dex: 715 },
  { name: "ゼルネアス", slug: "xerneas", dex: 716 },
  { name: "イベルタル", slug: "yveltal", dex: 717 },
  { name: "ジガルデ", slug: "zygarde", dex: 718 },
  { name: "ジュナイパー", slug: "decidueye", dex: 724 },
  { name: "ガオガエン", slug: "incineroar", dex: 727 },
  { name: "アシレーヌ", slug: "primarina", dex: 730 },
  { name: "ルガルガン", slug: "lycanroc", dex: 745 },
  { name: "ドヒドイデ", slug: "toxapex", dex: 748 },
  { name: "キテルグマ", slug: "bewear", dex: 760 },
  { name: "ミミッキュ", slug: "mimikyu", dex: 778 },
  { name: "ジャラランガ", slug: "kommoo", dex: 784 },
  { name: "カプ・コケコ", slug: "tapukoko", dex: 785 },
  { name: "カプ・テテフ", slug: "tapulele", dex: 786 },
  { name: "カプ・ブルル", slug: "tapubulu", dex: 787 },
  { name: "カプ・レヒレ", slug: "tapufini", dex: 788 },
  { name: "ソルガレオ", slug: "solgaleo", dex: 791 },
  { name: "ルナアーラ", slug: "lunala", dex: 792 },
  { name: "ネクロズマ", slug: "necrozma", dex: 800 },
  { name: "マーシャドー", slug: "marshadow", dex: 802 },
  { name: "ゴリランダー", slug: "rillaboom", dex: 812 },
  { name: "エースバーン", slug: "cinderace", dex: 815 },
  { name: "インテレオン", slug: "inteleon", dex: 818 },
  { name: "アーマーガア", slug: "corviknight", dex: 823 },
  { name: "ポットデス", slug: "polteageist", dex: 855 },
  { name: "オーロンゲ", slug: "grimmsnarl", dex: 861 },
  { name: "ドラパルト", slug: "dragapult", dex: 887 },
  { name: "ザシアン", slug: "zacian", dex: 888 },
  { name: "ザマゼンタ", slug: "zamazenta", dex: 889 },
  { name: "ムゲンダイナ", slug: "eternatus", dex: 890 },
  { name: "ウーラオス", slug: "urshifu", dex: 892 },
  { name: "ウーラオス(連撃)", slug: "urshifu-rapidstrike", dex: 892 },
  { name: "レジエレキ", slug: "regieleki", dex: 894 },
  { name: "レジドラゴ", slug: "regidrago", dex: 895 },
  { name: "ブリザポス", slug: "glastrier", dex: 896 },
  { name: "レイスポス", slug: "spectrier", dex: 897 },
  { name: "バドレックス", slug: "calyrex", dex: 898 },
  { name: "バドレックス(白馬)", slug: "calyrex-ice", dex: 898 },
  { name: "バドレックス(黒馬)", slug: "calyrex-shadow", dex: 898 },
  { name: "ガチグマ", slug: "ursaluna", dex: 901 },
  { name: "ガチグマ(アカツキ)", slug: "ursaluna-bloodmoon", dex: 901 },
  { name: "オオニューラ", slug: "sneasler", dex: 903 },
  // Gen 9 - SV
  { name: "ニャオハ", slug: "sprigatito", dex: 906 },
  { name: "ホゲータ", slug: "fuecoco", dex: 909 },
  { name: "マスカーニャ", slug: "meowscarada", dex: 911 },
  { name: "クワッス", slug: "quaxly", dex: 912 },
  { name: "ラウドボーン", slug: "skeledirge", dex: 914 },
  { name: "ウェーニバル", slug: "quaquaval", dex: 915 },
  { name: "グルトン", slug: "lechonk", dex: 916 },
  { name: "パフュートン", slug: "oinkologne", dex: 917 },
  { name: "パモット", slug: "pawmo", dex: 922 },
  { name: "パーモット", slug: "pawmot", dex: 923 },
  { name: "イッカネズミ", slug: "maushold", dex: 925 },
  { name: "オリーヴァ", slug: "arboliva", dex: 929 },
  { name: "キョジオーン", slug: "garganacl", dex: 934 },
  { name: "グレンアルマ", slug: "armarouge", dex: 936 },
  { name: "ソウブレイズ", slug: "ceruledge", dex: 937 },
  { name: "ハラバリー", slug: "bellibolt", dex: 939 },
  { name: "マフィティフ", slug: "mabosstiff", dex: 942 },
  { name: "リククラゲ", slug: "toedscruel", dex: 948 },
  { name: "ウミトリオ", slug: "wugtrio", dex: 961 },
  { name: "キラフロル", slug: "glimmora", dex: 970 },
  { name: "ヘイラッシャ", slug: "dondozo", dex: 977 },
  { name: "シャリタツ", slug: "tatsugiri", dex: 978 },
  { name: "コノヨザル", slug: "annihilape", dex: 979 },
  { name: "ドオー", slug: "clodsire", dex: 980 },
  { name: "ドドゲザン", slug: "kingambit", dex: 983 },
  { name: "イダイナキバ", slug: "greattusk", dex: 984 },
  { name: "サケブシッポ", slug: "screamtail", dex: 985 },
  { name: "アラブルタケ", slug: "brutebonnet", dex: 986 },
  { name: "ハバタクカミ", slug: "fluttermane", dex: 987 },
  { name: "チヲハウハネ", slug: "slitherwing", dex: 988 },
  { name: "スナノケガワ", slug: "sandyshocks", dex: 989 },
  { name: "テツノワダチ", slug: "irontreads", dex: 990 },
  { name: "テツノツツミ", slug: "ironbundle", dex: 991 },
  { name: "テツノカイナ", slug: "ironhands", dex: 992 },
  { name: "テツノコウベ", slug: "ironjugulis", dex: 993 },
  { name: "テツノドクガ", slug: "ironmoth", dex: 994 },
  { name: "テツノブジン", slug: "ironvaliant", dex: 995 },
  { name: "テツノイバラ", slug: "ironthorns", dex: 996 },
  { name: "セグレイブ", slug: "baxcalibur", dex: 998 },
  { name: "サーフゴー", slug: "gholdengo", dex: 1000 },
  { name: "チオンジェン", slug: "wochien", dex: 1001 },
  { name: "パオジアン", slug: "chienpao", dex: 1002 },
  { name: "ディンルー", slug: "tinglu", dex: 1003 },
  { name: "イーユイ", slug: "chiyu", dex: 1004 },
  { name: "トドロクツキ", slug: "roaringmoon", dex: 1005 },
  { name: "コライドン", slug: "koraidon", dex: 1007 },
  { name: "ミライドン", slug: "miraidon", dex: 1008 },
  { name: "ウネルミナモ", slug: "walkingwake", dex: 1009 },
  { name: "テツノイサハ", slug: "ironleaves", dex: 1010 },
  { name: "カミッチュ", slug: "dipplin", dex: 1011 },
  { name: "イイネイヌ", slug: "okidogi", dex: 1014 },
  { name: "マシマシラ", slug: "munkidori", dex: 1015 },
  { name: "キチキギス", slug: "fezandipiti", dex: 1016 },
  { name: "オーガポン", slug: "ogerpon", dex: 1017 },
  { name: "ブリジュラス", slug: "archaludon", dex: 1018 },
  { name: "カミツオロチ", slug: "hydrapple", dex: 1019 },
  { name: "タケルライコ", slug: "ragingbolt", dex: 1021 },
  { name: "テツノカシラ", slug: "ironcrown", dex: 1023 },
  { name: "テラパゴス", slug: "terapagos", dex: 1024 },
  // Galarian forms
  { name: "フリーザー(ガラル)", slug: "articuno-galar", dex: 144 },
  { name: "サンダー(ガラル)", slug: "zapdos-galar", dex: 145 },
  { name: "ファイヤー(ガラル)", slug: "moltres-galar", dex: 146 },
  // Added for レギュレーションM-A (pokemonchampions 2026-04-08)
  { name: "スピアー", slug: "beedrill", dex: 15 },
  { name: "ピジョット", slug: "pidgeot", dex: 18 },
  { name: "アーボック", slug: "arbok", dex: 24 },
  { name: "ライチュウ (アローラのすがた)", slug: "raichu-alola", dex: 26 },
  { name: "キュウコン (アローラのすがた)", slug: "ninetales-alola", dex: 38 },
  { name: "ウインディ (ヒスイのすがた)", slug: "arcanine-hisui", dex: 59 },
  { name: "ヤドラン (ガラルのすがた)", slug: "slowbro-galar", dex: 80 },
  { name: "ケンタロス (パルデアのすがた・コンバットしゅ)", slug: "tauros-paldeacombat", dex: 128 },
  { name: "ケンタロス (パルデアのすがた・ブレイズしゅ)", slug: "tauros-paldeablaze", dex: 128 },
  { name: "ケンタロス (パルデアのすがた・ウォーターしゅ)", slug: "tauros-paldeaaqua", dex: 128 },
  { name: "プテラ", slug: "aerodactyl", dex: 142 },
  { name: "バクフーン (ヒスイのすがた)", slug: "typhlosion-hisui", dex: 157 },
  { name: "アリアドス", slug: "ariados", dex: 168 },
  { name: "デンリュウ", slug: "ampharos", dex: 181 },
  { name: "マリルリ", slug: "azumarill", dex: 184 },
  { name: "ニョロトノ", slug: "politoed", dex: 186 },
  { name: "ヤドキング (ガラルのすがた)", slug: "slowking-galar", dex: 199 },
  { name: "フォレトス", slug: "forretress", dex: 205 },
  { name: "エアームド", slug: "skarmory", dex: 227 },
  { name: "ヘルガー", slug: "houndoom", dex: 229 },
  { name: "チルタリス", slug: "altaria", dex: 334 },
  { name: "ポワルン", slug: "castform", dex: 351 },
  { name: "ジュペッタ", slug: "banette", dex: 354 },
  { name: "チリーン", slug: "chimecho", dex: 358 },
  { name: "オニゴーリ", slug: "glalie", dex: 362 },
  { name: "ラムパルド", slug: "rampardos", dex: 409 },
  { name: "トリデプス", slug: "bastiodon", dex: 411 },
  { name: "ミミロップ", slug: "lopunny", dex: 428 },
  { name: "ドクロッグ", slug: "toxicroak", dex: 454 },
  { name: "ユキノオー", slug: "abomasnow", dex: 460 },
  { name: "ロトム (ロトムのすがた)", slug: "rotom", dex: 479 },
  { name: "ロトム (ヒートロトム)", slug: "rotom-heat", dex: 479 },
  { name: "ロトム (ウォッシュロトム)", slug: "rotom-wash", dex: 479 },
  { name: "ロトム (フロストロトム)", slug: "rotom-frost", dex: 479 },
  { name: "ロトム (スピンロトム)", slug: "rotom-fan", dex: 479 },
  { name: "ロトム (カットロトム)", slug: "rotom-mow", dex: 479 },
  { name: "ダイケンキ (ヒスイのすがた)", slug: "samurott-hisui", dex: 503 },
  { name: "ミルホッグ", slug: "watchog", dex: 505 },
  { name: "レパルダス", slug: "liepard", dex: 510 },
  { name: "ヤナッキー", slug: "simisage", dex: 512 },
  { name: "バオッキー", slug: "simisear", dex: 514 },
  { name: "ヒヤッキー", slug: "simipour", dex: 516 },
  { name: "タブンネ", slug: "audino", dex: 531 },
  { name: "ワルビアル", slug: "krookodile", dex: 553 },
  { name: "デスカーン", slug: "cofagrigus", dex: 563 },
  { name: "ダストダス", slug: "garbodor", dex: 569 },
  { name: "ゾロアーク (ヒスイのすがた)", slug: "zoroark-hisui", dex: 571 },
  { name: "ランクルス", slug: "reuniclus", dex: 579 },
  { name: "バイバニラ", slug: "vanilluxe", dex: 584 },
  { name: "エモンガ", slug: "emolga", dex: 587 },
  { name: "シャンデラ", slug: "chandelure", dex: 609 },
  { name: "ツンベアー", slug: "beartic", dex: 614 },
  { name: "マッギョ", slug: "stunfisk", dex: 618 },
  { name: "マッギョ (ガラルのすがた)", slug: "stunfisk-galar", dex: 618 },
  { name: "ゴルーグ", slug: "golurk", dex: 623 },
  { name: "ウルガモス", slug: "volcarona", dex: 637 },
  { name: "ブリガロン", slug: "chesnaught", dex: 652 },
  { name: "マフォクシー", slug: "delphox", dex: 655 },
  { name: "ホルード", slug: "diggersby", dex: 660 },
  { name: "ビビヨン", slug: "vivillon", dex: 666 },
  { name: "フラエッテ", slug: "floette-eternal", dex: 670 },
  { name: "フラージェス", slug: "florges", dex: 671 },
  { name: "ゴロンダ", slug: "pangoro", dex: 675 },
  { name: "トリミアン", slug: "furfrou", dex: 676 },
  { name: "ニャオニクス (オスのすがた)", slug: "meowstic", dex: 678 },
  { name: "ニャオニクス (メスのすがた)", slug: "meowstic-f", dex: 678 },
  { name: "フレフワン", slug: "aromatisse", dex: 683 },
  { name: "ペロリーム", slug: "slurpuff", dex: 685 },
  { name: "ブロスター", slug: "clawitzer", dex: 693 },
  { name: "エレザード", slug: "heliolisk", dex: 695 },
  { name: "ガチゴラス", slug: "tyrantrum", dex: 697 },
  { name: "アマルルガ", slug: "aurorus", dex: 699 },
  { name: "ルチャブル", slug: "hawlucha", dex: 701 },
  { name: "デデンネ", slug: "dedenne", dex: 702 },
  { name: "ヌメルゴン (ヒスイのすがた)", slug: "goodra-hisui", dex: 706 },
  { name: "オーロット", slug: "trevenant", dex: 709 },
  { name: "パンプジン (ちゅうだましゅ)", slug: "gourgeist", dex: 711 },
  { name: "パンプジン (こだましゅ)", slug: "gourgeist-small", dex: 711 },
  { name: "パンプジン (おおだましゅ)", slug: "gourgeist-large", dex: 711 },
  { name: "パンプジン (ギガだましゅ)", slug: "gourgeist-super", dex: 711 },
  { name: "クレベース", slug: "avalugg", dex: 713 },
  { name: "クレベース (ヒスイのすがた)", slug: "avalugg-hisui", dex: 713 },
  { name: "ジュナイパー (ヒスイのすがた)", slug: "decidueye-hisui", dex: 724 },
  { name: "ドデカバシ", slug: "toucannon", dex: 733 },
  { name: "ケケンカニ", slug: "crabominable", dex: 740 },
  { name: "ルガルガン (まひるのすがた)", slug: "lycanroc", dex: 745 },
  { name: "ルガルガン (まよなかのすがた)", slug: "lycanroc-midnight", dex: 745 },
  { name: "ルガルガン (たそがれのすがた)", slug: "lycanroc-dusk", dex: 745 },
  { name: "バンバドロ", slug: "mudsdale", dex: 750 },
  { name: "オニシズクモ", slug: "araquanid", dex: 752 },
  { name: "エンニュート", slug: "salazzle", dex: 758 },
  { name: "アマージョ", slug: "tsareena", dex: 763 },
  { name: "ヤレユータン", slug: "oranguru", dex: 765 },
  { name: "ナゲツケサル", slug: "passimian", dex: 766 },
  { name: "ジジーロン", slug: "drampa", dex: 780 },
  { name: "アップリュー", slug: "flapple", dex: 841 },
  { name: "タルップル", slug: "appletun", dex: 842 },
  { name: "サダイジャ", slug: "sandaconda", dex: 844 },
  { name: "ブリムオン", slug: "hatterene", dex: 858 },
  { name: "バリコオル", slug: "mrrime", dex: 866 },
  { name: "デスバーン", slug: "runerigus", dex: 867 },
  { name: "マホイップ", slug: "alcremie", dex: 869 },
  { name: "モルペコ", slug: "morpeko", dex: 877 },
  { name: "アヤシシ", slug: "wyrdeer", dex: 899 },
  { name: "バサギリ", slug: "kleavor", dex: 900 },
  { name: "イダイトウ (オスのすがた)", slug: "basculegion", dex: 902 },
  { name: "イダイトウ (メスのすがた)", slug: "basculegion-f", dex: 902 },
  { name: "スコヴィラン", slug: "scovillain", dex: 952 },
  { name: "クエスパトラ", slug: "espathra", dex: 956 },
  { name: "デカヌチャン", slug: "tinkaton", dex: 959 },
  { name: "イルカマン", slug: "palafin", dex: 964 },
  { name: "ミミズズ", slug: "orthworm", dex: 968 },
  { name: "リキキリン", slug: "farigiraf", dex: 981 },
  { name: "ヤバソチャ", slug: "sinistcha", dex: 1013 },
  // Mega Evolutions
  { name: "メガフシギバナ", slug: "venusaur-mega", dex: 3 },
  { name: "メガリザードンX", slug: "charizard-megax", dex: 6 },
  { name: "メガリザードンY", slug: "charizard-megay", dex: 6 },
  { name: "メガカメックス", slug: "blastoise-mega", dex: 9 },
  { name: "メガスピアー", slug: "beedrill-mega", dex: 15 },
  { name: "メガピジョット", slug: "pidgeot-mega", dex: 18 },
  { name: "メガフーディン", slug: "alakazam-mega", dex: 65 },
  { name: "メガヤドラン", slug: "slowbro-mega", dex: 80 },
  { name: "メガゲンガー", slug: "gengar-mega", dex: 94 },
  { name: "メガガルーラ", slug: "kangaskhan-mega", dex: 115 },
  { name: "メガカイロス", slug: "pinsir-mega", dex: 127 },
  { name: "メガギャラドス", slug: "gyarados-mega", dex: 130 },
  { name: "メガプテラ", slug: "aerodactyl-mega", dex: 142 },
  { name: "メガデンリュウ", slug: "ampharos-mega", dex: 181 },
  { name: "メガハガネール", slug: "steelix-mega", dex: 208 },
  { name: "メガハッサム", slug: "scizor-mega", dex: 212 },
  { name: "メガヘラクロス", slug: "heracross-mega", dex: 214 },
  { name: "メガヘルガー", slug: "houndoom-mega", dex: 229 },
  { name: "メガバンギラス", slug: "tyranitar-mega", dex: 248 },
  { name: "メガサーナイト", slug: "gardevoir-mega", dex: 282 },
  { name: "メガヤミラミ", slug: "sableye-mega", dex: 302 },
  { name: "メガボスゴドラ", slug: "aggron-mega", dex: 306 },
  { name: "メガチャーレム", slug: "medicham-mega", dex: 308 },
  { name: "メガライボルト", slug: "manectric-mega", dex: 310 },
  { name: "メガサメハダー", slug: "sharpedo-mega", dex: 319 },
  { name: "メガバクーダ", slug: "camerupt-mega", dex: 323 },
  { name: "メガチルタリス", slug: "altaria-mega", dex: 334 },
  { name: "メガジュペッタ", slug: "banette-mega", dex: 354 },
  { name: "メガアブソル", slug: "absol-mega", dex: 357 },
  { name: "メガオニゴーリ", slug: "glalie-mega", dex: 362 },
  { name: "メガガブリアス", slug: "garchomp-mega", dex: 445 },
  { name: "メガルカリオ", slug: "lucario-mega", dex: 448 },
  { name: "メガユキノオー", slug: "abomasnow-mega", dex: 460 },
  { name: "メガミミロップ", slug: "lopunny-mega", dex: 428 },
  { name: "メガエルレイド", slug: "gallade-mega", dex: 475 },
  { name: "メガタブンネ", slug: "audino-mega", dex: 531 },
  // M-A regulation custom Mega Evolutions
  { name: "メガピクシー", slug: "clefable-mega", dex: 36 },
  { name: "メガウツボット", slug: "victreebel-mega", dex: 71 },
  { name: "メガスターミー", slug: "starmie-mega", dex: 121 },
  { name: "メガカイリュー", slug: "dragonite-mega", dex: 149 },
  { name: "メガメガニウム", slug: "meganium-mega", dex: 154 },
  { name: "メガオーダイル", slug: "feraligatr-mega", dex: 160 },
  { name: "メガエアームド", slug: "skarmory-mega", dex: 227 },
  { name: "メガチリーン", slug: "chimecho-mega", dex: 358 },
  { name: "メガユキメノコ", slug: "froslass-mega", dex: 478 },
  { name: "メガエンブオー", slug: "emboar-mega", dex: 500 },
  { name: "メガドリュウズ", slug: "excadrill-mega", dex: 530 },
  { name: "メガシャンデラ", slug: "chandelure-mega", dex: 609 },
  { name: "メガゴルーグ", slug: "golurk-mega", dex: 623 },
  { name: "メガブリガロン", slug: "chesnaught-mega", dex: 652 },
  { name: "メガマフォクシー", slug: "delphox-mega", dex: 655 },
  { name: "メガゲッコウガ", slug: "greninja-mega", dex: 658 },
  { name: "メガフラエッテ", slug: "floette-mega", dex: 670 },
  { name: "メガニャオニクス", slug: "meowstic", dex: 678 },
  { name: "メガルチャブル", slug: "hawlucha-mega", dex: 701 },
  { name: "メガケケンカニ", slug: "crabominable-mega", dex: 740 },
  { name: "メガジジーロン", slug: "drampa-mega", dex: 780 },
  { name: "メガスコヴィラン", slug: "scovillain-mega", dex: 952 },
  { name: "メガキラフロル", slug: "glimmora-mega", dex: 970 },
];

// Mega evolution mapping: base form → mega form(s)
const MEGA_MAP = {};
const MEGA_BASE = {};
[
  ["フシギバナ", ["メガフシギバナ"]],
  ["リザードン", ["メガリザードンX", "メガリザードンY"]],
  ["カメックス", ["メガカメックス"]],
  ["スピアー", ["メガスピアー"]],
  ["ピジョット", ["メガピジョット"]],
  ["フーディン", ["メガフーディン"]],
  ["ヤドラン", ["メガヤドラン"]],
  ["ゲンガー", ["メガゲンガー"]],
  ["ガルーラ", ["メガガルーラ"]],
  ["カイロス", ["メガカイロス"]],
  ["ギャラドス", ["メガギャラドス"]],
  ["プテラ", ["メガプテラ"]],
  ["デンリュウ", ["メガデンリュウ"]],
  ["ハガネール", ["メガハガネール"]],
  ["ハッサム", ["メガハッサム"]],
  ["ヘラクロス", ["メガヘラクロス"]],
  ["ヘルガー", ["メガヘルガー"]],
  ["バンギラス", ["メガバンギラス"]],
  ["サーナイト", ["メガサーナイト"]],
  ["ヤミラミ", ["メガヤミラミ"]],
  ["ボスゴドラ", ["メガボスゴドラ"]],
  ["チャーレム", ["メガチャーレム"]],
  ["ライボルト", ["メガライボルト"]],
  ["サメハダー", ["メガサメハダー"]],
  ["バクーダ", ["メガバクーダ"]],
  ["チルタリス", ["メガチルタリス"]],
  ["ジュペッタ", ["メガジュペッタ"]],
  ["アブソル", ["メガアブソル"]],
  ["オニゴーリ", ["メガオニゴーリ"]],
  ["ガブリアス", ["メガガブリアス"]],
  ["ルカリオ", ["メガルカリオ"]],
  ["ユキノオー", ["メガユキノオー"]],
  ["ミミロップ", ["メガミミロップ"]],
  ["エルレイド", ["メガエルレイド"]],
  ["タブンネ", ["メガタブンネ"]],
  // M-A regulation custom megas
  ["ピクシー", ["メガピクシー"]],
  ["ウツボット", ["メガウツボット"]],
  ["スターミー", ["メガスターミー"]],
  ["カイリュー", ["メガカイリュー"]],
  ["メガニウム", ["メガメガニウム"]],
  ["オーダイル", ["メガオーダイル"]],
  ["エアームド", ["メガエアームド"]],
  ["チリーン", ["メガチリーン"]],
  ["ユキメノコ", ["メガユキメノコ"]],
  ["エンブオー", ["メガエンブオー"]],
  ["ドリュウズ", ["メガドリュウズ"]],
  ["シャンデラ", ["メガシャンデラ"]],
  ["ゴルーグ", ["メガゴルーグ"]],
  ["ブリガロン", ["メガブリガロン"]],
  ["マフォクシー", ["メガマフォクシー"]],
  ["ゲッコウガ", ["メガゲッコウガ"]],
  ["フラエッテ", ["メガフラエッテ"]],
  ["ニャオニクス (オスのすがた)", ["メガニャオニクス"]],
  ["ニャオニクス (メスのすがた)", ["メガニャオニクス"]],
  ["ルチャブル", ["メガルチャブル"]],
  ["ケケンカニ", ["メガケケンカニ"]],
  ["ジジーロン", ["メガジジーロン"]],
  ["スコヴィラン", ["メガスコヴィラン"]],
  ["キラフロル", ["メガキラフロル"]],
].forEach(([base, megas]) => {
  MEGA_MAP[base] = megas;
  megas.forEach(m => { MEGA_BASE[m] = base; });
});

// Remove duplicates by name
const seen = new Set();
const POKEMON_DB = POKEMON_LIST.filter(p => {
  if (seen.has(p.name)) return false;
  seen.add(p.name);
  return true;
}).sort((a, b) => a.name.localeCompare(b.name, 'ja'));

// Build lookup maps
const POKEMON_BY_NAME = {};
POKEMON_DB.forEach(p => {
  POKEMON_BY_NAME[p.name] = p;
});

// ===== Japanese search helpers =====
// Katakana ↔ Hiragana conversion (Unicode offset 0x60)
function toHiragana(str) {
  return str.replace(/[\u30a1-\u30f6]/g, ch =>
    String.fromCharCode(ch.charCodeAt(0) - 0x60)
  );
}

// Convert katakana (or hiragana) to Hepburn-style romaji.
// Only the kana portion is converted; ASCII/symbols are preserved (lowercased).
// Handles digraphs (キャ/シャ/ファ/ヴァ…), 促音 ッ, 撥音 ン, 長音 ー.
const ROMAJI_DIGRAPH = {
  'キャ': 'kya', 'キュ': 'kyu', 'キョ': 'kyo',
  'シャ': 'sha', 'シュ': 'shu', 'ショ': 'sho', 'シェ': 'she',
  'チャ': 'cha', 'チュ': 'chu', 'チョ': 'cho', 'チェ': 'che',
  'ニャ': 'nya', 'ニュ': 'nyu', 'ニョ': 'nyo',
  'ヒャ': 'hya', 'ヒュ': 'hyu', 'ヒョ': 'hyo',
  'ミャ': 'mya', 'ミュ': 'myu', 'ミョ': 'myo',
  'リャ': 'rya', 'リュ': 'ryu', 'リョ': 'ryo',
  'ギャ': 'gya', 'ギュ': 'gyu', 'ギョ': 'gyo',
  'ジャ': 'ja',  'ジュ': 'ju',  'ジョ': 'jo',  'ジェ': 'je',
  'ヂャ': 'ja',  'ヂュ': 'ju',  'ヂョ': 'jo',
  'ビャ': 'bya', 'ビュ': 'byu', 'ビョ': 'byo',
  'ピャ': 'pya', 'ピュ': 'pyu', 'ピョ': 'pyo',
  'ファ': 'fa',  'フィ': 'fi',  'フェ': 'fe',  'フォ': 'fo', 'フュ': 'fyu',
  'ウィ': 'wi',  'ウェ': 'we',  'ウォ': 'wo',
  'ヴァ': 'va',  'ヴィ': 'vi',  'ヴェ': 've',  'ヴォ': 'vo', 'ヴュ': 'vyu',
  'ティ': 'ti',  'トゥ': 'tu',  'テュ': 'tyu',
  'ディ': 'di',  'ドゥ': 'du',  'デュ': 'dyu',
  'ツァ': 'tsa', 'ツィ': 'tsi', 'ツェ': 'tse', 'ツォ': 'tso',
  'イェ': 'ye',
};
const ROMAJI_MONO = {
  'ア': 'a',  'イ': 'i',  'ウ': 'u',  'エ': 'e',  'オ': 'o',
  'カ': 'ka', 'キ': 'ki', 'ク': 'ku', 'ケ': 'ke', 'コ': 'ko',
  'サ': 'sa', 'シ': 'shi','ス': 'su', 'セ': 'se', 'ソ': 'so',
  'タ': 'ta', 'チ': 'chi','ツ': 'tsu','テ': 'te', 'ト': 'to',
  'ナ': 'na', 'ニ': 'ni', 'ヌ': 'nu', 'ネ': 'ne', 'ノ': 'no',
  'ハ': 'ha', 'ヒ': 'hi', 'フ': 'fu', 'ヘ': 'he', 'ホ': 'ho',
  'マ': 'ma', 'ミ': 'mi', 'ム': 'mu', 'メ': 'me', 'モ': 'mo',
  'ヤ': 'ya', 'ユ': 'yu', 'ヨ': 'yo',
  'ラ': 'ra', 'リ': 'ri', 'ル': 'ru', 'レ': 're', 'ロ': 'ro',
  'ワ': 'wa', 'ヰ': 'wi', 'ヱ': 'we', 'ヲ': 'wo', 'ン': 'n',
  'ガ': 'ga', 'ギ': 'gi', 'グ': 'gu', 'ゲ': 'ge', 'ゴ': 'go',
  'ザ': 'za', 'ジ': 'ji', 'ズ': 'zu', 'ゼ': 'ze', 'ゾ': 'zo',
  'ダ': 'da', 'ヂ': 'ji', 'ヅ': 'zu', 'デ': 'de', 'ド': 'do',
  'バ': 'ba', 'ビ': 'bi', 'ブ': 'bu', 'ベ': 'be', 'ボ': 'bo',
  'パ': 'pa', 'ピ': 'pi', 'プ': 'pu', 'ペ': 'pe', 'ポ': 'po',
  'ヴ': 'vu',
  'ァ': 'a',  'ィ': 'i',  'ゥ': 'u',  'ェ': 'e',  'ォ': 'o',
  'ャ': 'ya', 'ュ': 'yu', 'ョ': 'yo',
};

function toRomaji(str) {
  // First promote any hiragana to katakana so tables cover both.
  const kata = str.replace(/[\u3041-\u3096]/g, ch =>
    String.fromCharCode(ch.charCodeAt(0) + 0x60)
  );

  let out = '';
  let i = 0;
  while (i < kata.length) {
    const ch = kata[i];
    const next = kata[i + 1];

    // 促音 ッ: double next consonant
    if (ch === 'ッ') {
      const pair = next ? kata.substr(i + 1, 2) : '';
      const nextRomaji = ROMAJI_DIGRAPH[pair] || ROMAJI_MONO[next] || '';
      if (nextRomaji) out += nextRomaji[0];
      i++;
      continue;
    }

    // 長音 ー: repeat previous vowel
    if (ch === 'ー') {
      const prev = out[out.length - 1];
      if (prev && 'aeiou'.includes(prev)) out += prev;
      i++;
      continue;
    }

    // Digraph (2-char kana)
    if (next) {
      const two = ch + next;
      if (ROMAJI_DIGRAPH[two]) {
        out += ROMAJI_DIGRAPH[two];
        i += 2;
        continue;
      }
    }

    // Mono kana
    if (ROMAJI_MONO[ch]) {
      out += ROMAJI_MONO[ch];
      i++;
      continue;
    }

    // ASCII / symbols / unknown — pass through lowercased
    out += ch.toLowerCase();
    i++;
  }
  return out;
}

// Precompute searchable forms (hiragana + romaji) for each Pokemon.
POKEMON_DB.forEach(p => {
  p.searchHira = toHiragana(p.name).toLowerCase();
  p.searchRomaji = toRomaji(p.name);
});

// Sprite URL helper
function getSpriteUrl(slug) {
  return `https://play.pokemonshowdown.com/sprites/gen5/${slug}.png`;
}

// ===== Item List =====
// Source: https://gamewith.jp/pokemon-champions/546487
// Grouped categories are stored as-is (e.g. "メガストーン") instead of individual items.
const ITEM_LIST = [
  // Grouped categories
  "メガストーン",
  "タイプ強化",
  "半減実",
  "状態異常回復きのみ",
  // Individual items
  "きあいのタスキ",
  "こだわりスカーフ",
  "たべのこし",
  "きあいのハチマキ",
  "ピントレンズ",
  "しろいハーブ",
  "メンタルハーブ",
  "ひかりのこな",
  "せんせいのツメ",
  "おうじゃのしるし",
  "かいがらのすず",
  "でんきだま",
  // Individual berries
  "ラムのみ",
  "オボンのみ",
  "オレンのみ",
  "ヒメリのみ",
];

// ===== Regulation Allowlists =====
// rule name → list of allowed Pokemon names (from POKEMON_DB).
// Source: https://web-view.app.pokemonchampions.jp/battle/pages/events/rs177501629259kmzbny/ja/pokemon.html
//         https://news.pokemon-home.com/ja/page/751.html (レギュレーションM-A, 2026-04-08〜2026-06-17)
const REGULATION_POKEMON = {
  "レギュレーションM-A": [
    "フシギバナ",
    "リザードン",
    "カメックス",
    "スピアー",
    "ピジョット",
    "アーボック",
    "ピカチュウ",
    "ライチュウ",
    "ライチュウ (アローラのすがた)",
    "ピクシー",
    "キュウコン",
    "キュウコン (アローラのすがた)",
    "ウインディ",
    "ウインディ (ヒスイのすがた)",
    "フーディン",
    "カイリキー",
    "ウツボット",
    "ヤドラン",
    "ヤドラン (ガラルのすがた)",
    "ゲンガー",
    "ガルーラ",
    "スターミー",
    "カイロス",
    "ケンタロス",
    "ケンタロス (パルデアのすがた・コンバットしゅ)",
    "ケンタロス (パルデアのすがた・ブレイズしゅ)",
    "ケンタロス (パルデアのすがた・ウォーターしゅ)",
    "ギャラドス",
    "メタモン",
    "シャワーズ",
    "サンダース",
    "ブースター",
    "プテラ",
    "カビゴン",
    "カイリュー",
    "メガニウム",
    "バクフーン",
    "バクフーン (ヒスイのすがた)",
    "オーダイル",
    "アリアドス",
    "デンリュウ",
    "マリルリ",
    "ニョロトノ",
    "エーフィ",
    "ブラッキー",
    "ヤドキング",
    "ヤドキング (ガラルのすがた)",
    "フォレトス",
    "ハガネール",
    "ハッサム",
    "ヘラクロス",
    "エアームド",
    "ヘルガー",
    "バンギラス",
    "ペリッパー",
    "サーナイト",
    "ヤミラミ",
    "ボスゴドラ",
    "チャーレム",
    "ライボルト",
    "サメハダー",
    "バクーダ",
    "コータス",
    "チルタリス",
    "ミロカロス",
    "ポワルン",
    "ジュペッタ",
    "チリーン",
    "アブソル",
    "オニゴーリ",
    "ドダイトス",
    "ゴウカザル",
    "エンペルト",
    "レントラー",
    "ロズレイド",
    "ラムパルド",
    "トリデプス",
    "ミミロップ",
    "ミカルゲ",
    "ガブリアス",
    "ルカリオ",
    "カバルドン",
    "ドクロッグ",
    "ユキノオー",
    "マニューラ",
    "ドサイドン",
    "リーフィア",
    "グレイシア",
    "グライオン",
    "マンムー",
    "エルレイド",
    "ユキメノコ",
    "ロトム (ロトムのすがた)",
    "ロトム (ヒートロトム)",
    "ロトム (ウォッシュロトム)",
    "ロトム (フロストロトム)",
    "ロトム (スピンロトム)",
    "ロトム (カットロトム)",
    "ジャローダ",
    "エンブオー",
    "ダイケンキ",
    "ダイケンキ (ヒスイのすがた)",
    "ミルホッグ",
    "レパルダス",
    "ヤナッキー",
    "バオッキー",
    "ヒヤッキー",
    "ドリュウズ",
    "タブンネ",
    "ローブシン",
    "エルフーン",
    "ワルビアル",
    "デスカーン",
    "ダストダス",
    "ゾロアーク",
    "ゾロアーク (ヒスイのすがた)",
    "ランクルス",
    "バイバニラ",
    "エモンガ",
    "シャンデラ",
    "ツンベアー",
    "マッギョ",
    "マッギョ (ガラルのすがた)",
    "ゴルーグ",
    "サザンドラ",
    "ウルガモス",
    "ブリガロン",
    "マフォクシー",
    "ゲッコウガ",
    "ホルード",
    "ファイアロー",
    "ビビヨン",
    "フラエッテ",
    "フラージェス",
    "ゴロンダ",
    "トリミアン",
    "ニャオニクス (オスのすがた)",
    "ニャオニクス (メスのすがた)",
    "ギルガルド",
    "フレフワン",
    "ペロリーム",
    "ブロスター",
    "エレザード",
    "ガチゴラス",
    "アマルルガ",
    "ニンフィア",
    "ルチャブル",
    "デデンネ",
    "ヌメルゴン",
    "ヌメルゴン (ヒスイのすがた)",
    "クレッフィ",
    "オーロット",
    "パンプジン (ちゅうだましゅ)",
    "パンプジン (こだましゅ)",
    "パンプジン (おおだましゅ)",
    "パンプジン (ギガだましゅ)",
    "クレベース",
    "クレベース (ヒスイのすがた)",
    "オンバーン",
    "ジュナイパー",
    "ジュナイパー (ヒスイのすがた)",
    "ガオガエン",
    "アシレーヌ",
    "ドデカバシ",
    "ケケンカニ",
    "ルガルガン (まひるのすがた)",
    "ルガルガン (まよなかのすがた)",
    "ルガルガン (たそがれのすがた)",
    "ドヒドイデ",
    "バンバドロ",
    "オニシズクモ",
    "エンニュート",
    "アマージョ",
    "ヤレユータン",
    "ナゲツケサル",
    "ミミッキュ",
    "ジジーロン",
    "ジャラランガ",
    "アーマーガア",
    "アップリュー",
    "タルップル",
    "サダイジャ",
    "ポットデス",
    "ブリムオン",
    "バリコオル",
    "デスバーン",
    "マホイップ",
    "モルペコ",
    "ドラパルト",
    "アヤシシ",
    "バサギリ",
    "イダイトウ (オスのすがた)",
    "イダイトウ (メスのすがた)",
    "オオニューラ",
    "マスカーニャ",
    "ラウドボーン",
    "ウェーニバル",
    "イッカネズミ",
    "キョジオーン",
    "グレンアルマ",
    "ソウブレイズ",
    "ハラバリー",
    "スコヴィラン",
    "クエスパトラ",
    "デカヌチャン",
    "イルカマン",
    "ミミズズ",
    "キラフロル",
    "リキキリン",
    "ドドゲザン",
    "ヤバソチャ",
    "ブリジュラス",
    "カミツオロチ",
    // Mega Evolutions
    "メガフシギバナ",
    "メガリザードンX",
    "メガリザードンY",
    "メガカメックス",
    "メガスピアー",
    "メガピジョット",
    "メガフーディン",
    "メガヤドラン",
    "メガゲンガー",
    "メガガルーラ",
    "メガカイロス",
    "メガギャラドス",
    "メガプテラ",
    "メガデンリュウ",
    "メガハガネール",
    "メガハッサム",
    "メガヘラクロス",
    "メガヘルガー",
    "メガバンギラス",
    "メガサーナイト",
    "メガヤミラミ",
    "メガボスゴドラ",
    "メガチャーレム",
    "メガライボルト",
    "メガサメハダー",
    "メガバクーダ",
    "メガチルタリス",
    "メガジュペッタ",
    "メガアブソル",
    "メガオニゴーリ",
    "メガガブリアス",
    "メガルカリオ",
    "メガユキノオー",
    "メガミミロップ",
    "メガエルレイド",
    "メガタブンネ",
    // M-A regulation custom megas
    "メガピクシー",
    "メガウツボット",
    "メガスターミー",
    "メガカイリュー",
    "メガメガニウム",
    "メガオーダイル",
    "メガエアームド",
    "メガチリーン",
    "メガユキメノコ",
    "メガエンブオー",
    "メガドリュウズ",
    "メガシャンデラ",
    "メガゴルーグ",
    "メガブリガロン",
    "メガマフォクシー",
    "メガゲッコウガ",
    "メガフラエッテ",
    "メガニャオニクス",
    "メガルチャブル",
    "メガケケンカニ",
    "メガジジーロン",
    "メガスコヴィラン",
    "メガキラフロル",
  ],
};

const REGULATION_POKEMON_SET = {};
Object.keys(REGULATION_POKEMON).forEach(key => {
  REGULATION_POKEMON_SET[key] = new Set(REGULATION_POKEMON[key]);
});
